"""empty message

Revision ID: 1098d698e7a5
Revises: 
Create Date: 2019-11-30 18:16:28.082777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1098d698e7a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
