"""empty message

Revision ID: 47a8d147b553
Revises: d9c8f317f003
Create Date: 2019-12-13 11:52:44.104321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a8d147b553'
down_revision = 'd9c8f317f003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow', sa.Column('follower_id', sa.Integer(), nullable=True))
    op.add_column('follow', sa.Column('following_id', sa.Integer(), nullable=True))
    op.drop_constraint('follow_following_fkey', 'follow', type_='foreignkey')
    op.drop_constraint('follow_follower_fkey', 'follow', type_='foreignkey')
    op.create_foreign_key(None, 'follow', 'users', ['following_id'], ['id'])
    op.create_foreign_key(None, 'follow', 'users', ['follower_id'], ['id'])
    op.drop_column('follow', 'following')
    op.drop_column('follow', 'follower')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow', sa.Column('follower', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('follow', sa.Column('following', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.create_foreign_key('follow_follower_fkey', 'follow', 'users', ['follower'], ['id'])
    op.create_foreign_key('follow_following_fkey', 'follow', 'users', ['following'], ['id'])
    op.drop_column('follow', 'following_id')
    op.drop_column('follow', 'follower_id')
    # ### end Alembic commands ###
