"""empty message

Revision ID: 91adb055439c
Revises: d3e46719d146
Create Date: 2019-12-15 09:42:00.902219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91adb055439c'
down_revision = 'd3e46719d146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('location', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'location')
    # ### end Alembic commands ###
