"""empty message

Revision ID: 9c76b54ba329
Revises: 1098d698e7a5
Create Date: 2019-12-01 11:38:38.981490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c76b54ba329'
down_revision = '1098d698e7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
