"""empty message

Revision ID: ba8ce61b040d
Revises: ade594101812
Create Date: 2019-12-04 14:09:39.938387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8ce61b040d'
down_revision = 'ade594101812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('uuid', sa.String(), nullable=True))
    op.drop_column('token', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('token', 'uuid')
    # ### end Alembic commands ###
