"""empty message

Revision ID: d3e46719d146
Revises: 
Create Date: 2019-12-15 09:33:45.703668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e46719d146'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
