"""empty message

Revision ID: de283fb4c217
Revises: c619505e1ef6
Create Date: 2019-12-11 16:23:33.620568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de283fb4c217'
down_revision = 'c619505e1ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('like_post_id_fkey', 'like', type_='foreignkey')
    op.drop_constraint('like_comment_id_fkey', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'comment', ['comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'like', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_comment_id_fkey', 'like', 'comment', ['comment_id'], ['id'])
    op.create_foreign_key('like_post_id_fkey', 'like', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
